<a href="https://colab.research.google.com/github/devinandana01/DeviProject/blob/main/Devi_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (2.1.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.26.4)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.10/dist-packages (from xgboost) (2.23.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.13.1)

In [2]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.10/dist-packages (0.12.4)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.13.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.5.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (3.5.0)

## IMPORTING LIBRARIES

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import StackingClassifier
import seaborn as sns
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.naive_bayes import GaussianNB
from numpy import argmax
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve, roc_auc_score
import random
import pandas as pd

from sklearn.preprocessing import LabelEncoder
import xgboost as xgb
from imblearn.over_sampling import SMOTE
from collections import Counter

## IMPORTING DATASET

In [8]:
df=pd.read_csv("transactions_df.csv")
df

,TRANSACTION_ID,TX_DATETIME,ACCOUNT_ID,TRANSACTION_TYPE,TX_AMOUNT,TX_TIME_SECONDS,TX_TIME_DAYS,TX_FRAUD,TX_FRAUD_SCENARIO,TX_AMOUNT_STD,TX_AMOUNT_MEAN,Amount_Deviation,Amount_Threshold,Time_Seconds_Diff,Time_Diff,TX_DURING_WEEKEND,TX_DURING_NIGHT,TX_FRAUD_1H_SCENARIO,ACCOUNT_ID_NB_TX_1H_WINDOW,ACCOUNT_ID_AVG_AMOUNT_1H_WINDOW
0,206,2023-04-01 02:03:24,1317,2,109726.21,7404,0,0,0,32384.484105,70990.724352,38735.485648,64768.968210,3278.0,3278.0,1,1,0,1.0,109726.21
1,210,2023-04-01 02:04:08,3131,3,47654.69,7448,0,0,0,14959.301807,32777.196782,14877.493218,29918.603613,1301.0,1301.0,1,1,0,1.0,47654.69
2,248,2023-04-01 02:19:19,746,2,48435.54,8359,0,0,0,19392.377010,40481.627412,7953.912588,38784.754021,6741.0,6741.0,1,1,0,1.0,48435.54
3,253,2023-04-01 02:21:08,3166,3,154065.84,8468,0,1,3,34707.819695,77200.845531,76864.994469,69415.639390,3516.0,3516.0,1,1,0,1.0,154065.84
4,269,2023-04-01 02:26:53,1432,2,53070.56,8813,0,0,0,18953.101452,41070.573515,11999.986485,37906.202903,1378.0,1378.0,1,1,0,1.0,53070.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1755279,1760271,2023-09-30 23:58:19,4410,2,30797.10,15811099,182,0,0,24051.767660,50687.985324,-19890.885324,48103.535321,379700.0,379700.0,1,0,0,1.0,30797.10
1755280,1760272,2023-09-30 23:58:19,3681,2,23038.62,15811099,182,0,0,7136.890898,15888.629716,7149.990284,14273.781796,40692.0,40692.0,1,0,0,1.0,23038.62
1755281,1760273,2023-09-30 23:58:25,4657,1,68670.52,15811105,182,0,0,37607.193608,84875.116104,-16204.596104,75214.387216,34529.0,34529.0,1,0,0,1.0,68670.52
1755282,1760274,2023-09-30 23:58:34,4314,3,48549.57,15811114,182,0,0,35291.315650,75321.073282,-26771.503282,70582.631301,29642.0,29642.0,1,0,0,1.0,48549.57
1755283,1760275,2023-09-30 23:59:39,3971,2,20974.94,15811179,182,0,0,19673.199652,42618.740444,-21643.800444,39346.399303,25026.0,25026.0,1,0,0,1.0,20974.94